"use client";

import React, { useState } from "react";

const HeatCalculatorLighting = ({ onCalculate }) => {
  const [wattage, setWattage] = useState("");
  const [heatGenerated, setHeatGenerated] = useState(0);

  // Handle input change
  const handleChange = (e) => {
    const value = e.target.value;
    setWattage(value === "" ? "" : Math.max(0, parseFloat(value) || 0)); // Prevent negatives
  };

  // Manual calculation handler
  const calculateHeat = () => {
    if (wattage === "" || wattage <= 0) {
      setHeatGenerated(0);
      if (typeof onCalculate === "function") {
        onCalculate(0);
      }
      return;
    }

    const calculatedHeat = 3.4 * wattage * 0.8; // Q = 3.4 × WATT × 0.8
    setHeatGenerated(calculatedHeat);

    if (typeof onCalculate === "function") {
      onCalculate(calculatedHeat);
    }
  };

  return (
    <div className="p-6 bg-white rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4 text-blue-600">
        Heat Generated by Lighting
      </h2>

      {/* Wattage Input */}
      <div className="mb-4">
        <label className="block mb-1 font-medium">Lighting Wattage (W):</label>
        <input
          type="number"
          value={wattage}
          onChange={handleChange}
          className="w-full p-2 border rounded"
          placeholder="Enter Wattage"
          min="0"
        />
      </div>

      {/* Calculate Button */}
      <div className="flex justify-center mt-4">
        <button
          onClick={calculateHeat}
          className="bg-blue-600 text-white px-6 py-2 rounded hover:bg-blue-700 transition"
        >
          Calculate Heat
        </button>
      </div>

      {/* Result */}
      <div className="mt-6">
        {heatGenerated > 0 ? (
          <p className="text-lg">
            Heat Generated:{" "}
            <strong>{heatGenerated.toFixed(2)} BTU/hr</strong>
          </p>
        ) : (
          <p className="text-gray-600">
            Enter a valid wattage and click the button to calculate heat.
          </p>
        )}
      </div>
    </div>
  );
};

export default HeatCalculatorLighting;
